### PR TITLE
Set up initial project and implement baseline inference pipeline with reasoning configuration

### PR DESCRIPTION
**Pull request by AVS1508**
## Changelog ##

- Updated README with initial setup info 
- Ignore Python caches/temps 
- Updated README with set-up instructions 
- Added preliminary source code and placeholders 
- Refactored the main file and implemented baseline reasoning pipeline 
- Added argument parsing for ease of deploying batch jobs 
- Added the required reasoning configuration for the GSM8K dataset 
- Implemented utilities for use with the main LLM inference pipeline 
- Developed the baseline LLM inference pipeline 
- Replaced placeholders with actual experiment commands and results 
- Dumped logs for example of how to log information 
- Added changes to reasoning source code for additional arguments and cleaning up code 
- Added a small example output as expected when running the code without modified arguments 
- Updated requirements with new dependencies 
- Updated README with new details

### CODE REVIEW

**Comment by AVS1508** [comment]
This PR is ready for review!

**Comment by AVS1508** [comment]
This PR is now ready for review! @sahilgupta17 @dhrp01 @AadamLok

**Comment by AadamLok** [comment]
Concerns discussed offline. And changes made accordingly.

**Review by AadamLok — APPROVED** [review]
Everything looks good.

**Pull request merged**
